### ISSUE TITLE
Why AGPL license ?

### ISSUE THREAD

**Issue by TheBricktop** [riccardolops/GodotVolumetricRendering#1]
Its kinda punishing license for anybody wanting to use this piece of software. LGPL 3 would be enough to enforce openness of plugin while alowing people to do their commercial work.

**Comment by TheBricktop** [comment]
Yeah but it not only asks to publish changes to code of the library that was originally licensed as agpl but also extends to any other code that is connected to it, and sometimes it is not even possible if You use a proprietary lib in the stack. Also from my understanding affero actually extends even to the server/backend code that You might use and usually commercial servers are often closedsource.

**Comment by riccardolops** [comment]
I changed the license so now it can be used in proprietary projects.

**Comment by TheBricktop** [comment]
Much appreciated.
