### ISSUE TITLE
Transfer function editor, with histogram

### ISSUE THREAD

**Issue by mlavik1** [riccardolops/GodotVolumetricRendering#10]
Hi! Regarding the "A cooler way to edit the transfer function with the histogram of the density values" point on the [README](https://github.com/riccardolops/GodotVolumetricRendering/blob/main/README.md).

Is this something you're already working on, or would you like me to have a look at it?

And if so, do you have any thoughts on how it should look and behave? Just something similar to the one in the Unity plugin?

I guess the advantage of Godot is that there's *one* UI system, so the TF editor should be usable both in editor and "in-game" :sunglasses:

**Comment by riccardolops** [comment]
Hi @mlavik1!
What I have in mind is something similar to what you did in the Unity plugin. It's true that currently, you can change the color and alpha points of the two gradients from the inspector, but having a histogram of the density values would be better, in my opinion.
I haven't started working on it yet, so if you already have ideas on how to implement it, please feel free to begin! 😉

**Comment by mlavik1** [comment]
By the way, do we want to keep the feature that lets you edit the alpha and colour gradients separately in the editor as well? Or should I remove those?

Also, the TransferFunction class has its own list of alpha/control points, in addition to the alpha/colour gradients. I suppose we don't need both. Godot's Gradient is quite nice, so maybe we'll just go with that one? :)

**Comment by riccardolops** [comment]
Since I'm also somewhat new to Godot, I used two gradients while I was porting your solution. In fact, as I was writing this, I didn't yet fully understand how Godot's Gradient worked. 😅
So yeah, I think we can remove the TransferFunction's list of alpha/colour points.
Good work, by the way! With this, I can now better see which colours corresponds to which grayscale values! 😎

**Comment by mlavik1** [comment]
Yeah I'm learning some new things here too (I didnt' know about the Gradient class before I saw your code - and that's quite nice acutally!)

I'm changing it so that TransferFunction now is a `Resource`, so we can save and load them as other resources. And I'm making a custom inspector with a "show transfer function editor button".
![image](https://github.com/riccardolops/GodotVolumetricRendering/assets/6906872/43dbdeb0-e6ec-4711-9b7e-df0211ed1468)

I suppose I can also add a utility method for showing the TF editor in-game. After that I'll make a PR :)
