### ISSUE TITLE
Install GodotVolumeRendering issues

### ISSUE THREAD

**Issue by kimjohn1** [riccardolops/GodotVolumetricRendering#15]
I am unable to get GodotVolumeRendering installed in Godot.  I download the GodotVolumetricRendering-0.0.0-alpha.zip file from the Releases page.  Unpack the compressed folder, and move it to my Documents directory.  I open Godot (v4.3 stable), create a new project, name it GodotVolumeRendering, and drag and drop the addons folder from /Documents/GodotVolumetricRendering-0.0.0-alpha to the res://folder in the Godot application FileSystem panel.  When I open Project, Project Settings, Plugins tab, I see that VolumetricDatasetImporter is listed,  When I click the Enabled, On checkbox I get a small dialog that indicates: Unable to load addon script from path: 'res://addons/volumetric_importer/VolumetricImporter.cs'.

I note that the VolumetricImporter.cs script is actually located in addons/volumetric_importer/scripts/VolumetricImporter.cs', but even if I paste a copy in addons/volumetric_importer I still get the dialog indicating unable to load.

Do you have any suggestions for me to get this addon loaded and enabled in Godot?

Thanks,
Kim

**Comment by riccardolops** [comment]
Hi Kim,

Great news—the latest release of the Godot Volumetric Rendering plugin should work now! To get it running smoothly, please follow these steps:

1. **Compile the C# Project**: Before enabling the plugin in Godot, ensure that you compile the C# project associated with the plugin. This step is essential for generating the necessary binaries.

2. **Enable the Plugin**: After compiling, go to Project > Project Settings > Plugins tab in Godot and enable the VolumetricDatasetImporter plugin.

If you run into any further issues after these steps, feel free to reach out, and I’ll be happy to help!

Best,  
Riccardo
