### ISSUE TITLE
please start github discussion

### ISSUE THREAD

**Issue by GeorgeS2019** [riccardolops/GodotVolumetricRendering#2]
Not familiar how to control the thickness of the 3D volume

**Comment by riccardolops** [comment]
I started a github discussion for this repo, please can you explain what do you mean by thickness of the 3D volume?

**Comment by GeorgeS2019** [comment]
Perhaps the DICOM data I have only provides a thin slice of a 3D model. 

Could you share which Volume data you used that provides what we see in the screenshot?

**Comment by riccardolops** [comment]
I just pushed a .nrrd and a dicom series, please note that in order to load a dicom series the entire containing folder needs to be selected
